config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create] do
    resources :dashboard, only: [:index]
    resources :workouts do  
      resources :cardio_exercises, except: [:index]
        resources :cardio_activity, only: [:index], module: :cardio_exercises
      resources :strength_exercises do
        resources :lift_sets
      end
      resources :muscle_group, only: [:index, :show], module: :strength_exercises
    end
  end

  resources :muscle_group, only: [:index, :show]
  resources :cardio_activity, only: [:index]
  namespace :admin do 
    resources :users
  end

  resources :maps, only: [:index]
  
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/login', to: "sessions#destroy"

  root to: "root_director#index"

end

app/models/activity_muscle_group.rb
class ActivityMuscleGroup < ApplicationRecord
  belongs_to :muscle_group
  belongs_to :strength_activity
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cardio_activity.rb
class CardioActivity < ApplicationRecord
  validates :name, presence: :true, uniqueness: :true
  has_many :cardio_exercises,  dependent: :destroy
end

app/models/cardio_exercise.rb
class CardioExercise < ApplicationRecord
  validates :duration, presence: :true
  validates :distance, presence: :true
  belongs_to :workout
  belongs_to :cardio_activity
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  def self.number_of_days_active(id)
    Workout.where(user_id: id).distinct.pluck(:date).count
  end
  
  def total_strength_workouts(id)
    Workout.where(user_id: id).where(category: 1).count
  end
  
  def total_cardio_workouts(id)
    Workout.where(user_id: id).where(category: 0).count
  end
  
  def total_mileage(id)
    Workout.where(user_id: id).joins(:cardio_exercises).sum(:distance)
  end


  def average_mileage
    Workout.where(user_id: id).joins(:cardio_exercises).average(:distance)
  end
  
  def most_popular_activity(id)
    ids = Workout.where(user_id: id).pluck(:id)
    CardioExercise.joins(:cardio_activity).where(workout_id: ids).group(:name).count(:name)
    StrengthExercise.joins(:strength_activity).where(workout_id: ids).group(:name).count(:name)
  end
  
end

app/models/lift_set.rb
class LiftSet < ApplicationRecord
  validates :weight, presence: :true
  validates :reps, presence: :true
  belongs_to :strength_exercise
end

app/models/muscle_group.rb
class MuscleGroup < ApplicationRecord
  validates :name, presence: :true, uniqueness: :true
  has_many :activity_muscle_groups,  dependent: :destroy
  has_many :strength_activities, through: :activity_muscle_groups
end

app/models/strength_activity.rb
class StrengthActivity < ApplicationRecord
  validates :name, presence: :true, uniqueness: :true
  has_many :activity_muscle_groups,  dependent: :destroy
  has_many :muscle_groups, through: :activity_muscle_groups
end

app/models/strength_exercise.rb
class StrengthExercise < ApplicationRecord
  belongs_to :workout
  belongs_to :strength_activity
  has_many :lift_sets, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: :true, uniqueness: :true
  validates :first_name, :last_name, presence: :true
  has_many :workouts, dependent: :destroy
  enum role: [:user, :admin]
end

app/models/workout.rb
class Workout < ApplicationRecord
  validates :name, presence: :true
  validates :date, presence: :true
  validates :category, presence: :true
  belongs_to :user
  has_many :cardio_exercises, dependent: :destroy
  has_many :strength_exercises, dependent: :destroy
  enum category: [:cardio, :strength]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user.admin?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    binding.pry
  end
end

app/controllers/lift_sets_controller.rb
class LiftSetsController < ApplicationController
  before_action :set_workout
  before_action :set_strength_exercise
  before_action :set_lift_set, only: [:edit, :update, :destroy]
  
  def new
    @lift_set = LiftSet.new
  end

  def create
    @lift_set = @exercise.lift_sets.new(lift_set_params)
    if @lift_set.save
      flash[:success] = "Set Added"
      redirect_to user_workout_strength_exercise_path(current_user, @workout, @exercise)
    else
      render :new
    end
  end
  
  def edit
  end

  def update
    @lift_set.update(lift_set_params)
    if @lift_set.save
      flash[:success] = "Exercise updated!"
      redirect_to user_workout_strength_exercise_path(current_user, @workout, @exercise)
    else
      render :edit
    end
  end

  def destroy
    @lift_set.destroy
    redirect_to user_workout_strength_exercise_path(current_user, @workout, @exercise)
  end

  private

    def lift_set_params
      params.require(:lift_set).permit(:weight, :reps)
    end
    
    def set_workout
      @workout = Workout.find(params[:workout_id])
    end

    def set_lift_set
      @lift_set = LiftSet.find(params[:id])
    end

    def set_strength_exercise
      @exercise = StrengthExercise.find(params[:strength_exercise_id])
    end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  

  def index
    ip = request.remote_ip
    ip_location = check_ip(ip)
    @location ={ zipcode: ip_location['zip_code'], latitude: ip_location['latitude'], longitude: ip_location['longitude']}
    @api_key = "AIzaSyCwdTm2xiTCPxTGZr_O7HsvVaQb8nKrS3o"
  end

  private

    def check_ip(ip)
      if Geocoder.search("#{ip}").first.data["zip_code"].nil?
        Geocoder.search("73.169.17.36").first.data
      else
        Geocoder.search("#{ip}").first.data
      end
    end
end

app/controllers/muscle_group_controller.rb
class MuscleGroupController < ApplicationController
  def index
    @categories = MuscleGroup.order(:name)
  end

  def show
    @category = MuscleGroup.find(params[:id])
    @strength_activities = @category.strength_activities.order(:name)
  end
end

app/controllers/root_director_controller.rb
class RootDirectorController < ApplicationController
  def index
    if current_user
      redirect_to user_dashboard_index_path(current_user)
    else
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController <ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:success] = "Successfully Logged In. Welcome #{@user.first_name.capitalize}!"
      redirect_to user_dashboard_index_path(@user)
    else
      flash[:concern] = "Missing Username or Password"
      render :new
    end
  end

  def destroy
    session.clear
    flash[:success] = "Logout Successful"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController<ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "User Successfully Created, Welcome #{@user.first_name.capitalize}"
      redirect_to user_dashboard_index_path(@user)
    else
      render :new
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :password)
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController<ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  def index
    @workouts = current_user.workouts
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = current_user.workouts.new(workout_params)
    if @workout.save
      redirect_to user_workout_path(current_user, @workout)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @workout.update(workout_params)
    if @workout.save
      flash[:success] = "#{@workout.name} udated!"
      redirect_to user_workouts_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @workout.destroy
    redirect_to user_workouts_path(current_user)
  end

    private

    def workout_params
      result = params.require(:workout).permit(:name, :date, :category)
      result[:category] = result[:category].to_i
      result
    end

    def set_workout
      @workout = Workout.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/muscle_group_helper.rb
module MuscleGroupHelper
  def search_string(activity)
    activity.downcase.split.join("+")
  end
end

app/views/dashboard/_chart1.html.haml
=javascript_include_tag "https://www.gstatic.com/charts/loader.js"
:javascript
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawVisualization);
    function drawVisualization() {
        var data = google.visualization.arrayToDataTable([
          ["#{escape_javascript @activities[1]}", "#{escape_javascript @activities[2]}", "#{escape_javascript @activities[0]}", "#{escape_javascript @activities[1]}"],
          [10,  10,  10, 10],
          [6,  8,  1, 10],

        ]);
        var options = {
            title : 'Ride Stats Based on Temperature',
            vAxis: {title: 'Number of Rides'},
            hAxis: {title: 'Temperature'},
            seriesType: 'bars',
        };
        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }

%div#chart_div{ :style => "width: 900px; height: 250px;"}

app/views/dashboard/index.html.haml
%div.page-header.text-center#center-header
  %h1 
    =current_user.first_name.capitalize
    's Dashboard
%div.container.dashboard.text-center
  %div.row
    %div.col-md-3
      %h3 Number of Days Active:
  %div.row    
    %div.col-md-3
      %h3 Longest Streak:
  %div.row
    %div.col-md-3
      %h3 Total Strength Workouts:
  %div.row
    %div.col-md-3
      %h3 Total Cardio Workouts:
  %div.row
    %div.col-md-3
      %h3 Total Mileage:
  %div.row
    %div.col-md-3
      %h3 Most Popular Activity:


-# = render partial: "chart1"

app/views/workouts/_form.html.haml
%div.list-group-item#workouts
  .form-horizontal
    =form_for([current_user, @workout]) do |f|
      %div.form-group
        =f.label :name
        =f.text_field :name
      %div.form-group  
        =f.label :date
        =f.date_select :date
      %div.form-group  
        =f.select :category, [["Cardio", 0], ["Strength", 1]]
      %div.form-group  
        %p=f.submit

  

app/views/workouts/edit.html.haml
%div.page-header.text-center#center-header
  %h2 Edit Workout
%div.container
  %div.row.text-center
    %div.col-md-6.col-md-offset-3
      
      =render partial: "shared/errors", locals: {target: @workout}
      =render partial: "form"

app/views/workouts/index.html.haml
%div.page-header.text-center#center-header
  %h2 Workouts
%div.container
  %div.row.text-center
    %div.col-md-6.col-md-offset-3
      %div.list-group
      - @workouts.each do |workout|
        %div.list-group-item#workouts
          %h3.list-group-item-heading= link_to "#{workout.name} - #{workout.category.capitalize}", user_workout_path(current_user, workout)
          %p= workout.date.strftime("%A, %B %e %Y")
          %div.inner-path
            = link_to "Edit", edit_user_workout_path(current_user, workout)
            = link_to "Delete", user_workout_path(current_user, workout), method: "delete"
      %div.list-group#workouts
        .path=link_to "Add New Workout", new_user_workout_path(current_user)

app/views/workouts/new.html.haml
%div.page-header.text-center#center-header
  %h2 Create Workout
%div.container
  %div.row.text-center
    %div.col-md-6.col-md-offset-3
     
      =render partial: "shared/errors", locals: {target: @workout}
      =render partial: "form"

app/views/workouts/show.html.haml
%div.page-header.text-center#center-header
  %h2=@workout.name
  %h4=@workout.category.capitalize
%div.container
  %div.row.text-center
    %div.col-md-6.col-md-offset-3
      -if @workout.cardio?
        -@workout.cardio_exercises.each do |exercise|
          %div.list-group#workouts
            %h3.list-group-item-heading=exercise.cardio_activity.name
            .list-group-item-text
              %p
                %strong Duration:
                =exercise.duration
              %p  
                %strong Distance:
                =exercise.distance
                miles
            = link_to "Edit",  edit_user_workout_cardio_exercise_path(current_user, @workout, exercise)
            = link_to "Delete", user_workout_cardio_exercise_path(current_user, @workout, exercise), method: "delete"
        %div.list-group#workouts
          %p=link_to "Add Exercise", new_user_workout_cardio_exercise_path(current_user, @workout)
          %p=link_to "Browse Exercises", user_workout_cardio_activity_index_path(current_user, @workout)

      -else
        -@workout.strength_exercises.each do |exercise|
          %div.list-group#workouts
            %h3.list-group-item-heading
              =link_to exercise.strength_activity.name, user_workout_strength_exercise_path(current_user, @workout, exercise)
            .list-group-item-text
              -exercise.lift_sets.each_with_index do |lift_set, i|
                %h4.list-group-item-heading
                  Set 
                  =(i+1)
                .list-group-item-text
                  %p 
                    %strong Weight:
                    =lift_set.weight
                    lbs
                  %p 
                    %strong Reps:
                    =lift_set.reps
            %div.inner-path       
              = link_to "Edit",  edit_user_workout_strength_exercise_path(current_user, @workout, exercise)
              = link_to "Delete", user_workout_strength_exercise_path(current_user, @workout, exercise), method: "delete"
        %div.list-group#workouts
          %p=link_to "Add Exercise", new_user_workout_strength_exercise_path(current_user, @workout)
          %p=link_to "Browse Exercises", user_workout_muscle_group_index_path(current_user, @workout)